export type TargetFieldAuthority = "CURRENT" | "TARGET" | "DERIVED"

export interface TargetFieldAuthorityRule {
  field: string
  authority: TargetFieldAuthority
  source: string
}

export const TARGET_FIELD_AUTHORITY = [
  {
    field: "Journey.revision",
    authority: "TARGET",
    source: "canonical transaction head",
  },
  {
    field: "JourneyEvent.parentSectionEventId",
    authority: "TARGET",
    source: "scope containment command",
  },
  {
    field: "JourneyEvent.placementStatus",
    authority: "TARGET",
    source: "place or unschedule command",
  },
  {
    field: "SectionEventDetail.localDate",
    authority: "TARGET",
    source: "DAY scheduling input",
  },
  {
    field: "CITY SectionEventDetail.timeZone",
    authority: "TARGET",
    source: "local-day planning scope",
  },
  {
    field: "SectionEvent.startAt/endAt/duration",
    authority: "DERIVED",
    source: "active child events in resolved projection",
  },
  {
    field: "JourneyEvent.planned values",
    authority: "TARGET",
    source: "planning commands",
  },
  {
    field: "JourneyEvent.actual values",
    authority: "TARGET",
    source: "execution confirmation commands",
  },
  {
    field: "JourneyEventLink.rank",
    authority: "TARGET",
    source: "scope-local ordering command",
  },
  {
    field: "JourneyBranchSelection.current",
    authority: "DERIVED",
    source: "latest append-only record without a superseder",
  },
  {
    field: "TransitEventDetail.activePlanningRunId",
    authority: "TARGET",
    source: "latest successful planning command",
  },
  {
    field: "TransitEventDetail.selectedPlanId",
    authority: "TARGET",
    source: "plan selection command within the active run",
  },
  {
    field: "ResolvedJourneyProjection.resolvedPosition",
    authority: "DERIVED",
    source: "current selected topology",
  },
  {
    field: "ResolvedJourneyProjection.locationOrdinal",
    authority: "DERIVED",
    source: "location events in resolved order",
  },
  {
    field: "WorkspaceSession.headGraph",
    authority: "TARGET",
    source: "persistent workspace command head",
  },
  {
    field: "WorkspaceDocument.accessState",
    authority: "DERIVED",
    source: "authenticated user, immutable owner, expiry",
  },
  {
    field: "WorkspaceDocument.draftState",
    authority: "DERIVED",
    source: "workspace/base revisions and pending persistence",
  },
  {
    field: "Travelogue body",
    authority: "DERIVED",
    source: "current topology plus confirmed actual facts",
  },
  {
    field: "Photo coordinate proximity",
    authority: "CURRENT",
    source: "legacy hint only; never Event ownership",
  },
] as const satisfies readonly TargetFieldAuthorityRule[]

export type TargetDeletionAction =
  | "RESTRICT"
  | "SOFT_DELETE"
  | "RETIRE"
  | "PRESERVE"
  | "EXPLICIT_PURGE"

export interface TargetDeletionRule {
  owner: string
  dependent: string
  ordinaryDelete: TargetDeletionAction
  hardPurge: TargetDeletionAction
}

export const TARGET_DELETION_MATRIX = [
  {
    owner: "User",
    dependent: "Journey",
    ordinaryDelete: "RESTRICT",
    hardPurge: "EXPLICIT_PURGE",
  },
  {
    owner: "Journey",
    dependent: "JourneyRevision",
    ordinaryDelete: "PRESERVE",
    hardPurge: "EXPLICIT_PURGE",
  },
  {
    owner: "Journey",
    dependent: "JourneyEvent",
    ordinaryDelete: "RETIRE",
    hardPurge: "EXPLICIT_PURGE",
  },
  {
    owner: "JourneyEvent",
    dependent: "JourneyEventLink",
    ordinaryDelete: "RETIRE",
    hardPurge: "EXPLICIT_PURGE",
  },
  {
    owner: "JourneyEvent",
    dependent: "TransitPlanningRun",
    ordinaryDelete: "PRESERVE",
    hardPurge: "EXPLICIT_PURGE",
  },
  {
    owner: "JourneyEvent",
    dependent: "EventAssetLink",
    ordinaryDelete: "RETIRE",
    hardPurge: "EXPLICIT_PURGE",
  },
  {
    owner: "JourneyEvent",
    dependent: "Asset",
    ordinaryDelete: "PRESERVE",
    hardPurge: "RESTRICT",
  },
  {
    owner: "SourcePack",
    dependent: "SourceDocument/SourceItem",
    ordinaryDelete: "SOFT_DELETE",
    hardPurge: "EXPLICIT_PURGE",
  },
  {
    owner: "WorkspaceSession",
    dependent: "WorkspaceRevision/Message/Suggestion/AgentRun",
    ordinaryDelete: "SOFT_DELETE",
    hardPurge: "EXPLICIT_PURGE",
  },
] as const satisfies readonly TargetDeletionRule[]

export const TARGET_IDEMPOTENCY_POLICY = {
  scope: "aggregate",
  sameKeySamePayload: "RETURN_ORIGINAL_RESULT",
  sameKeyDifferentPayload: "CONFLICT",
} as const

export type TargetRelationCardinality = "1:1" | "N:1"
export type TargetDeleteBehavior =
  | "CASCADE"
  | "RESTRICT"
  | "SET_NULL"
  | "NO_ACTION"

export interface TargetModelRelation {
  id: string
  fromModel: string
  fromFields: readonly string[]
  toModel: string
  toFields: readonly string[]
  cardinality: TargetRelationCardinality
  optional: boolean
  unique: boolean
  relationName: string
  onDelete: TargetDeleteBehavior
}

function relation(value: TargetModelRelation): TargetModelRelation {
  return value
}

export const TARGET_MODEL_RELATIONS = [
  relation({
    id: "session-user",
    fromModel: "Session",
    fromFields: ["userId"],
    toModel: "User",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "UserSessions",
    onDelete: "CASCADE",
  }),
  relation({
    id: "account-user",
    fromModel: "Account",
    fromFields: ["userId"],
    toModel: "User",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "UserAccounts",
    onDelete: "CASCADE",
  }),
  relation({
    id: "journey-owner",
    fromModel: "Journey",
    fromFields: ["ownerId"],
    toModel: "User",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "OwnedJourneys",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-revision-journey",
    fromModel: "JourneyRevision",
    fromFields: ["journeyId"],
    toModel: "Journey",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "JourneyRevisions",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-revision-parent",
    fromModel: "JourneyRevision",
    fromFields: ["journeyId", "parentRevisionId"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "id"],
    cardinality: "1:1",
    optional: true,
    unique: true,
    relationName: "JourneyRevisionLineage",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-revision-workspace-revision",
    fromModel: "JourneyRevision",
    fromFields: ["workspaceRevisionId"],
    toModel: "WorkspaceRevision",
    toFields: ["id"],
    cardinality: "1:1",
    optional: true,
    unique: true,
    relationName: "CommittedWorkspaceRevision",
    onDelete: "SET_NULL",
  }),
  relation({
    id: "journey-event-journey",
    fromModel: "JourneyEvent",
    fromFields: ["journeyId"],
    toModel: "Journey",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "JourneyEvents",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-event-parent-section",
    fromModel: "JourneyEvent",
    fromFields: ["journeyId", "parentSectionEventId"],
    toModel: "JourneyEvent",
    toFields: ["journeyId", "id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "SectionChildren",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-event-introduced-revision",
    fromModel: "JourneyEvent",
    fromFields: ["journeyId", "introducedRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "IntroducedJourneyEvents",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-event-retired-revision",
    fromModel: "JourneyEvent",
    fromFields: ["journeyId", "retiredRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "RetiredJourneyEvents",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-link-journey",
    fromModel: "JourneyEventLink",
    fromFields: ["journeyId"],
    toModel: "Journey",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "JourneyLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-link-from-event",
    fromModel: "JourneyEventLink",
    fromFields: ["journeyId", "fromEventId"],
    toModel: "JourneyEvent",
    toFields: ["journeyId", "id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "OutgoingJourneyLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-link-to-event",
    fromModel: "JourneyEventLink",
    fromFields: ["journeyId", "toEventId"],
    toModel: "JourneyEvent",
    toFields: ["journeyId", "id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "IncomingJourneyLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-link-introduced-revision",
    fromModel: "JourneyEventLink",
    fromFields: ["journeyId", "introducedRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "IntroducedJourneyLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "journey-link-retired-revision",
    fromModel: "JourneyEventLink",
    fromFields: ["journeyId", "retiredRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "RetiredJourneyLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "replacement-journey",
    fromModel: "JourneyEventReplacement",
    fromFields: ["journeyId"],
    toModel: "Journey",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "JourneyReplacements",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "replacement-predecessor",
    fromModel: "JourneyEventReplacement",
    fromFields: ["journeyId", "predecessorEventId"],
    toModel: "JourneyEvent",
    toFields: ["journeyId", "id"],
    cardinality: "1:1",
    optional: false,
    unique: true,
    relationName: "ReplacementPredecessor",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "replacement-successor",
    fromModel: "JourneyEventReplacement",
    fromFields: ["journeyId", "successorEventId"],
    toModel: "JourneyEvent",
    toFields: ["journeyId", "id"],
    cardinality: "1:1",
    optional: false,
    unique: true,
    relationName: "ReplacementSuccessor",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "replacement-revision",
    fromModel: "JourneyEventReplacement",
    fromFields: ["journeyId", "revision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "JourneyRevisionReplacements",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "branch-selection-journey",
    fromModel: "JourneyBranchSelection",
    fromFields: ["journeyId"],
    toModel: "Journey",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "JourneyBranchSelections",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "branch-selection-fork",
    fromModel: "JourneyBranchSelection",
    fromFields: ["journeyId", "forkEventId"],
    toModel: "JourneyEvent",
    toFields: ["journeyId", "id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "ForkSelections",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "branch-selection-link",
    fromModel: "JourneyBranchSelection",
    fromFields: ["journeyId", "selectedLinkId"],
    toModel: "JourneyEventLink",
    toFields: ["journeyId", "id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "SelectedBranchLink",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "branch-selection-supersedes",
    fromModel: "JourneyBranchSelection",
    fromFields: ["supersedesId"],
    toModel: "JourneyBranchSelection",
    toFields: ["id"],
    cardinality: "1:1",
    optional: true,
    unique: true,
    relationName: "BranchSelectionSupersession",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "branch-selection-revision",
    fromModel: "JourneyBranchSelection",
    fromFields: ["journeyId", "journeyRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "BranchSelectionRevision",
    onDelete: "RESTRICT",
  }),
  ...["Section", "Visit", "Transit", "Stay", "Meal", "Activity", "Note"].map(
    (kind) =>
      relation({
        id: `${kind.toLowerCase()}-detail-event`,
        fromModel: `${kind}EventDetail`,
        fromFields: ["eventId"],
        toModel: "JourneyEvent",
        toFields: ["id"],
        cardinality: "1:1",
        optional: false,
        unique: true,
        relationName: `${kind}EventDetail`,
        onDelete: "CASCADE",
      })
  ),
  relation({
    id: "section-detail-place",
    fromModel: "SectionEventDetail",
    fromFields: ["placeId"],
    toModel: "Place",
    toFields: ["id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "SectionEventPlace",
    onDelete: "SET_NULL",
  }),
  ...["Visit", "Stay", "Meal", "Activity"].flatMap((kind) => [
    relation({
      id: `${kind.toLowerCase()}-detail-planned-place`,
      fromModel: `${kind}EventDetail`,
      fromFields: ["plannedPlaceId"],
      toModel: "Place",
      toFields: ["id"],
      cardinality: "N:1",
      optional: true,
      unique: false,
      relationName: `${kind}PlannedPlace`,
      onDelete: "SET_NULL",
    }),
    relation({
      id: `${kind.toLowerCase()}-detail-actual-place`,
      fromModel: `${kind}EventDetail`,
      fromFields: ["actualPlaceId"],
      toModel: "Place",
      toFields: ["id"],
      cardinality: "N:1",
      optional: true,
      unique: false,
      relationName: `${kind}ActualPlace`,
      onDelete: "SET_NULL",
    }),
  ]),
  ...[
    ["planned-from", "plannedFromEventId", "TransitPlannedFrom"],
    ["planned-to", "plannedToEventId", "TransitPlannedTo"],
    ["actual-from", "actualFromEventId", "TransitActualFrom"],
    ["actual-to", "actualToEventId", "TransitActualTo"],
  ].map(([id, field, relationName]) =>
    relation({
      id: `transit-detail-${id}`,
      fromModel: "TransitEventDetail",
      fromFields: [field],
      toModel: "JourneyEvent",
      toFields: ["id"],
      cardinality: "N:1",
      optional: true,
      unique: false,
      relationName,
      onDelete: "SET_NULL",
    })
  ),
  relation({
    id: "transit-detail-active-run",
    fromModel: "TransitEventDetail",
    fromFields: ["eventId", "activePlanningRunId"],
    toModel: "TransitPlanningRun",
    toFields: ["transitEventId", "id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "ActiveTransitPlanningRun",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "transit-detail-selected-plan",
    fromModel: "TransitEventDetail",
    fromFields: ["eventId", "activePlanningRunId", "selectedPlanId"],
    toModel: "TransitPlan",
    toFields: ["transitEventId", "planningRunId", "id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "SelectedTransitPlan",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "transit-run-detail",
    fromModel: "TransitPlanningRun",
    fromFields: ["transitEventId"],
    toModel: "TransitEventDetail",
    toFields: ["eventId"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "TransitPlanningRuns",
    onDelete: "CASCADE",
  }),
  relation({
    id: "transit-plan-run",
    fromModel: "TransitPlan",
    fromFields: ["transitEventId", "planningRunId"],
    toModel: "TransitPlanningRun",
    toFields: ["transitEventId", "id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "TransitRunPlans",
    onDelete: "CASCADE",
  }),
  relation({
    id: "transit-segment-plan",
    fromModel: "TransitSegment",
    fromFields: ["transitPlanId"],
    toModel: "TransitPlan",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "TransitPlanSegments",
    onDelete: "CASCADE",
  }),
  relation({
    id: "workspace-owner",
    fromModel: "WorkspaceSession",
    fromFields: ["ownerId"],
    toModel: "User",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "OwnedWorkspaces",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "workspace-source-journey",
    fromModel: "WorkspaceSession",
    fromFields: ["sourceJourneyId"],
    toModel: "Journey",
    toFields: ["id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "JourneyWorkspaces",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "workspace-base-revision",
    fromModel: "WorkspaceSession",
    fromFields: ["sourceJourneyId", "baseJourneyRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "WorkspaceBaseJourneyRevision",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "workspace-revision-workspace",
    fromModel: "WorkspaceRevision",
    fromFields: ["workspaceId"],
    toModel: "WorkspaceSession",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "WorkspaceRevisions",
    onDelete: "CASCADE",
  }),
  relation({
    id: "workspace-revision-parent",
    fromModel: "WorkspaceRevision",
    fromFields: ["workspaceId", "parentRevisionId"],
    toModel: "WorkspaceRevision",
    toFields: ["workspaceId", "id"],
    cardinality: "1:1",
    optional: true,
    unique: true,
    relationName: "WorkspaceRevisionLineage",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "workspace-message-workspace",
    fromModel: "WorkspaceMessage",
    fromFields: ["workspaceId"],
    toModel: "WorkspaceSession",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "WorkspaceMessages",
    onDelete: "CASCADE",
  }),
  relation({
    id: "workspace-message-agent-run",
    fromModel: "WorkspaceMessage",
    fromFields: ["agentRunId"],
    toModel: "WorkspaceAgentRun",
    toFields: ["id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "AgentRunMessages",
    onDelete: "SET_NULL",
  }),
  relation({
    id: "workspace-suggestion-workspace",
    fromModel: "WorkspaceSuggestion",
    fromFields: ["workspaceId"],
    toModel: "WorkspaceSession",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "WorkspaceSuggestions",
    onDelete: "CASCADE",
  }),
  relation({
    id: "workspace-agent-run-workspace",
    fromModel: "WorkspaceAgentRun",
    fromFields: ["workspaceId"],
    toModel: "WorkspaceSession",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "WorkspaceAgentRuns",
    onDelete: "CASCADE",
  }),
  relation({
    id: "asset-owner",
    fromModel: "Asset",
    fromFields: ["ownerId"],
    toModel: "User",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "OwnedAssets",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "event-asset-link-event",
    fromModel: "EventAssetLink",
    fromFields: ["journeyId", "eventId"],
    toModel: "JourneyEvent",
    toFields: ["journeyId", "id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "EventAssetLinks",
    onDelete: "CASCADE",
  }),
  relation({
    id: "event-asset-link-journey",
    fromModel: "EventAssetLink",
    fromFields: ["journeyId"],
    toModel: "Journey",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "JourneyAssetLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "event-asset-link-introduced-revision",
    fromModel: "EventAssetLink",
    fromFields: ["journeyId", "introducedRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "IntroducedEventAssetLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "event-asset-link-retired-revision",
    fromModel: "EventAssetLink",
    fromFields: ["journeyId", "retiredRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "RetiredEventAssetLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "event-asset-link-asset",
    fromModel: "EventAssetLink",
    fromFields: ["assetId"],
    toModel: "Asset",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "AssetEventLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "observation-event",
    fromModel: "EventObservation",
    fromFields: ["eventId"],
    toModel: "JourneyEvent",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "EventObservations",
    onDelete: "CASCADE",
  }),
  relation({
    id: "observation-supersedes",
    fromModel: "EventObservation",
    fromFields: ["supersedesId"],
    toModel: "EventObservation",
    toFields: ["id"],
    cardinality: "1:1",
    optional: true,
    unique: true,
    relationName: "ObservationSupersession",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "source-pack-owner",
    fromModel: "SourcePack",
    fromFields: ["ownerId"],
    toModel: "User",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "OwnedSourcePacks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "source-document-pack",
    fromModel: "SourceDocument",
    fromFields: ["sourcePackId"],
    toModel: "SourcePack",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "SourcePackDocuments",
    onDelete: "CASCADE",
  }),
  relation({
    id: "source-document-asset",
    fromModel: "SourceDocument",
    fromFields: ["assetId"],
    toModel: "Asset",
    toFields: ["id"],
    cardinality: "1:1",
    optional: false,
    unique: true,
    relationName: "SourceDocumentAsset",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "source-item-document",
    fromModel: "SourceItem",
    fromFields: ["sourceDocumentId"],
    toModel: "SourceDocument",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "SourceDocumentItems",
    onDelete: "CASCADE",
  }),
  relation({
    id: "source-item-resolved-place",
    fromModel: "SourceItem",
    fromFields: ["resolvedPlaceId"],
    toModel: "Place",
    toFields: ["id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "ResolvedSourceItems",
    onDelete: "SET_NULL",
  }),
  relation({
    id: "place-alias-place",
    fromModel: "PlaceAlias",
    fromFields: ["placeId"],
    toModel: "Place",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "PlaceAliases",
    onDelete: "CASCADE",
  }),
  relation({
    id: "place-source-place",
    fromModel: "PlaceSource",
    fromFields: ["placeId"],
    toModel: "Place",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "PlaceSources",
    onDelete: "CASCADE",
  }),
  relation({
    id: "place-provider-match-place",
    fromModel: "PlaceProviderMatch",
    fromFields: ["placeId"],
    toModel: "Place",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "PlaceProviderMatches",
    onDelete: "CASCADE",
  }),
  relation({
    id: "provider-usage-user",
    fromModel: "ProviderUsageLog",
    fromFields: ["userId"],
    toModel: "User",
    toFields: ["id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "UserProviderUsage",
    onDelete: "SET_NULL",
  }),
  relation({
    id: "provider-usage-workspace",
    fromModel: "ProviderUsageLog",
    fromFields: ["workspaceId"],
    toModel: "WorkspaceSession",
    toFields: ["id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "WorkspaceProviderUsage",
    onDelete: "SET_NULL",
  }),
  relation({
    id: "provider-usage-agent-run",
    fromModel: "ProviderUsageLog",
    fromFields: ["agentRunId"],
    toModel: "WorkspaceAgentRun",
    toFields: ["id"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "AgentRunProviderUsage",
    onDelete: "SET_NULL",
  }),
  relation({
    id: "event-source-link-event",
    fromModel: "EventSourceLink",
    fromFields: ["journeyId", "eventId"],
    toModel: "JourneyEvent",
    toFields: ["journeyId", "id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "EventSourceLinks",
    onDelete: "CASCADE",
  }),
  relation({
    id: "event-source-link-journey",
    fromModel: "EventSourceLink",
    fromFields: ["journeyId"],
    toModel: "Journey",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "JourneySourceLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "event-source-link-introduced-revision",
    fromModel: "EventSourceLink",
    fromFields: ["journeyId", "introducedRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "IntroducedEventSourceLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "event-source-link-retired-revision",
    fromModel: "EventSourceLink",
    fromFields: ["journeyId", "retiredRevision"],
    toModel: "JourneyRevision",
    toFields: ["journeyId", "revision"],
    cardinality: "N:1",
    optional: true,
    unique: false,
    relationName: "RetiredEventSourceLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "event-source-link-item",
    fromModel: "EventSourceLink",
    fromFields: ["sourceItemId"],
    toModel: "SourceItem",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "SourceItemEventLinks",
    onDelete: "RESTRICT",
  }),
  relation({
    id: "event-source-link-document",
    fromModel: "EventSourceLink",
    fromFields: ["sourceDocumentId"],
    toModel: "SourceDocument",
    toFields: ["id"],
    cardinality: "N:1",
    optional: false,
    unique: false,
    relationName: "SourceDocumentEventLinks",
    onDelete: "RESTRICT",
  }),
] as const satisfies readonly TargetModelRelation[]

export const TARGET_MANDATORY_RELATION_IDS = [
  "session-user",
  "account-user",
  "journey-owner",
  "journey-revision-journey",
  "journey-revision-parent",
  "journey-revision-workspace-revision",
  "journey-event-journey",
  "journey-event-parent-section",
  "journey-event-introduced-revision",
  "journey-event-retired-revision",
  "journey-link-journey",
  "journey-link-from-event",
  "journey-link-to-event",
  "journey-link-introduced-revision",
  "journey-link-retired-revision",
  "replacement-journey",
  "replacement-predecessor",
  "replacement-successor",
  "replacement-revision",
  "branch-selection-journey",
  "branch-selection-fork",
  "branch-selection-link",
  "branch-selection-supersedes",
  "branch-selection-revision",
  "section-detail-event",
  "visit-detail-event",
  "transit-detail-event",
  "stay-detail-event",
  "meal-detail-event",
  "activity-detail-event",
  "note-detail-event",
  "section-detail-place",
  "visit-detail-planned-place",
  "visit-detail-actual-place",
  "stay-detail-planned-place",
  "stay-detail-actual-place",
  "meal-detail-planned-place",
  "meal-detail-actual-place",
  "activity-detail-planned-place",
  "activity-detail-actual-place",
  "transit-detail-planned-from",
  "transit-detail-planned-to",
  "transit-detail-actual-from",
  "transit-detail-actual-to",
  "transit-detail-active-run",
  "transit-detail-selected-plan",
  "transit-run-detail",
  "transit-plan-run",
  "transit-segment-plan",
  "workspace-owner",
  "workspace-source-journey",
  "workspace-base-revision",
  "workspace-revision-workspace",
  "workspace-revision-parent",
  "workspace-message-workspace",
  "workspace-message-agent-run",
  "workspace-suggestion-workspace",
  "workspace-agent-run-workspace",
  "asset-owner",
  "event-asset-link-event",
  "event-asset-link-journey",
  "event-asset-link-introduced-revision",
  "event-asset-link-retired-revision",
  "event-asset-link-asset",
  "observation-event",
  "observation-supersedes",
  "source-pack-owner",
  "source-document-pack",
  "source-document-asset",
  "source-item-document",
  "source-item-resolved-place",
  "place-alias-place",
  "place-source-place",
  "place-provider-match-place",
  "provider-usage-user",
  "provider-usage-workspace",
  "provider-usage-agent-run",
  "event-source-link-event",
  "event-source-link-journey",
  "event-source-link-introduced-revision",
  "event-source-link-retired-revision",
  "event-source-link-item",
  "event-source-link-document",
] as const
