import type { Route } from "@/types/route"

export const silkRoadRoute: Route = {
  id: "preset-silk-road",
  ownerId: "preset",
  version: 1,
  visibility: "private",
  name: "丝绸之路",
  description: "从长安出发，经河西走廊至西域的经典路线",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  nodes: [
    {
      id: "node-xian",
      routeId: "preset-silk-road",
      name: "西安",
      lat: 34.3416,
      lng: 108.9398,
      order: 0,
      category: "CITY",
      durationMinutes: 72 * 60,
      notes: "起点，兵马俑、大雁塔",
    },
    {
      id: "node-lanzhou",
      routeId: "preset-silk-road",
      name: "兰州",
      lat: 36.0611,
      lng: 103.8343,
      order: 1,
      category: "CITY",
      durationMinutes: 48 * 60,
      notes: "黄河风情线、牛肉面",
    },
    {
      id: "node-zhangye",
      routeId: "preset-silk-road",
      name: "张掖",
      lat: 38.9259,
      lng: 100.4498,
      order: 2,
      category: "CITY",
      durationMinutes: 48 * 60,
      notes: "七彩丹霞、大佛寺",
    },
    {
      id: "node-jiayuguan",
      routeId: "preset-silk-road",
      name: "嘉峪关",
      lat: 39.7728,
      lng: 98.2892,
      order: 3,
      category: "CITY",
      durationMinutes: 24 * 60,
      notes: "天下第一雄关",
    },
    {
      id: "node-dunhuang",
      routeId: "preset-silk-road",
      name: "敦煌",
      lat: 40.1421,
      lng: 94.6615,
      order: 4,
      category: "CITY",
      durationMinutes: 72 * 60,
      notes: "莫高窟、鸣沙山月牙泉",
    },
    {
      id: "node-turpan",
      routeId: "preset-silk-road",
      name: "吐鲁番",
      lat: 42.9513,
      lng: 89.1897,
      order: 5,
      category: "CITY",
      durationMinutes: 48 * 60,
      notes: "火焰山、葡萄沟",
    },
    {
      id: "node-urumqi",
      routeId: "preset-silk-road",
      name: "乌鲁木齐",
      lat: 43.8256,
      lng: 87.6168,
      order: 6,
      category: "CITY",
      durationMinutes: 48 * 60,
      notes: "终点，新疆首府",
    },
  ],
  edges: [
    ["node-xian", "node-lanzhou"],
    ["node-lanzhou", "node-zhangye"],
    ["node-zhangye", "node-jiayuguan"],
    ["node-jiayuguan", "node-dunhuang"],
    ["node-dunhuang", "node-turpan"],
    ["node-turpan", "node-urumqi"],
  ].map(([fromNodeId, toNodeId], index) => ({
    id: `edge-${index + 1}`,
    routeId: "preset-silk-road",
    fromNodeId,
    toNodeId,
    status: "INCOMPLETE",
    transportMode: "CAR",
    requestMode: "DRIVE",
    preference: "RECOMMENDED",
    planningStatus: "EMPTY",
  })),
  subPlans: [
    {
      id: "subplan-xian",
      routeNodeId: "node-xian",
      nodes: [
        {
          id: "subnode-xian-city-wall",
          subPlanId: "subplan-xian",
          name: "西安城墙",
          lat: 34.2655,
          lng: 108.9531,
          order: 0,
          category: "SIGHT",
          durationMinutes: 120,
          notes: "从南门登城，适合安排在抵达后的半日行程",
        },
        {
          id: "subnode-xian-dayan-pagoda",
          subPlanId: "subplan-xian",
          name: "大雁塔",
          lat: 34.2183,
          lng: 108.9642,
          order: 1,
          category: "SIGHT",
          durationMinutes: 90,
          notes: "傍晚可衔接大唐不夜城步行区",
        },
        {
          id: "subnode-xian-muslim-quarter",
          subPlanId: "subplan-xian",
          name: "回民街",
          lat: 34.263,
          lng: 108.945,
          order: 2,
          category: "RESTAURANT",
          durationMinutes: 90,
          notes: "作为晚餐和夜间散步节点",
        },
      ],
      edges: [
        {
          id: "subedge-xian-1",
          subPlanId: "subplan-xian",
          fromNodeId: "subnode-xian-city-wall",
          toNodeId: "subnode-xian-dayan-pagoda",
          status: "PLANNED",
          transportMode: "TAXI",
          requestMode: "DRIVE",
          planningStatus: "EMPTY",
          durationMinutes: 24,
          distanceKm: 8.8,
        },
        {
          id: "subedge-xian-2",
          subPlanId: "subplan-xian",
          fromNodeId: "subnode-xian-dayan-pagoda",
          toNodeId: "subnode-xian-muslim-quarter",
          status: "PLANNED",
          transportMode: "SUBWAY",
          requestMode: "TRANSIT",
          planningStatus: "EMPTY",
          durationMinutes: 32,
          distanceKm: 7.2,
        },
      ],
    },
  ],
}
